### ISSUE TITLE
java.lang.NoSuchFieldError: icons

### ISSUE THREAD

**Issue by Ristellise** [Reignofmagic/GTFO#4]
http://pastebin.com/MsRFSiZp here is an excrpt.
Note : works fine on client side. broken on server side

**Comment by Reignofmagic** [comment]
Yeah, I found that out myself a couple days ago. I've fixed most of the problem as of this point. Just need to get one more thing sorted, and it is not cooperating.

**Comment by Ristellise** [comment]
is it possible to make a dud folder with a bunch of random icons in it?

**Comment by Ristellise** [comment]
I found this about the same error on enderio. https://github.com/SleepyTrousers/EnderIO/commit/fa75db00f3445f6884f9220dfa314d4a856e1374

**Comment by Reignofmagic** [comment]
Hey thanks, the link to the EnderIO changes is what I needed. I was trying other things, but that wasn't working. The TLDR of the fix was move half a line of code from line 30 to line 53. Just uploaded the bugfix to the curseforge: Here is a  link to the download section
http://www.curse.com/mc-mods/minecraft/235912-gtfo-gems-are-truly-fabulous-and-outrageous#t1:other-downloads
Also pushing the new updated code to github. 
Link to the relevant file changes. Look at line 30 and 53
https://github.com/Reignofmagic/GTFO/blob/87928d2965eeee329a97047e9e9522ab0e9d70a3/src/main/java/com/reignofmagic/gems/blocks/gemOres.java

This release also includes 2 test items (torch and chest) essentially vanilla remakes, and a basis for me to use for the 1.2 release.

**Comment by Ristellise** [comment]
no problem! :smile:
